variables:
  ADVERTISED_HOST: 'spotify__kafka'
  ADVERTISED_PORT: '9092'
  AUTO_CREATE_TOPICS: 'true'

stages:
  - test

services:
  - spotify/kafka
  - postgres:9.4

before_script:
  - pip install -r requirements.txt
  - pip install -e .

lint:
  stage: test
  image: python:3.5
  script:
    - flake8 logpipe/ sandbox/

test_python:3.4:
  stage: test
  image: python:3.4
  script:
    - python sandbox/manage.py test logpipe.tests.unit

test_python:3.5:
  stage: test
  image: python:3.5
  script:
    - python sandbox/manage.py test logpipe.tests.unit
