variables:
  ADVERTISED_HOST: 'spotify__kafka'
  ADVERTISED_PORT: '9092'
  AUTO_CREATE_TOPICS: 'true'

stages:
  - lint

services:
  - spotify/kafka
  - postgres:9.4

cache:
  key: "$CI_PROJECT_NAME"
  paths:
    - $HOME/.cache/pip

before_script:
  - pip install tox

lint:
  stage: lint
  image: python:3.6
  script: tox -e lint

test_python34:
  stage: test
  image: python:3.4
  script: tox -e 'py34-django{19,110,111}'

test_python35:
  stage: test
  image: python:3.5
  script: tox -e 'py35-django{19,110,111}'

test_python36:
  stage: test
  image: python:3.6
  script: tox -e 'py36-django{19,110,111}'
