version: '2'
services:
  spotify__kafka:
    image: spotify/kafka
    environment:
      ADVERTISED_HOST: 'spotify__kafka'
      ADVERTISED_PORT: '9092'
      AUTO_CREATE_TOPICS: 'true'
  postgres:
    image: postgres:9.4
  test:
    build: .
    command: python sandbox/manage.py runserver 0.0.0.0:8000
    ports:
      - "8000:8000"
    depends_on:
      - spotify__kafka
      - postgres
    volumes:
      - .:/code
